name: starcoin_wallet

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.1.2
  convert: ^2.1.1
  fixnum: ^0.10.9
  bip39: ^1.0.3
  ed25519_dart_base: ^0.0.1
  sha3: 0.1.1
  optional: '5.0.0'
  http: 0.12.2

dev_dependencies:
 flutter_test:
    sdk: flutter
